interface=wlan1
driver=nl80211
ssid=robotcar
hw_mode=a
channel=36
country_code=JP
ieee80211n=1
ieee80211ac=1
wmm_enabled=1
ht_capab=[SHORT-GI-20]
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=robotcar1234
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
ap_max_inactivity=3600
disassoc_low_ack=0
wpa_group_rekey=86400
