#!/usr/bin/env python3
"""protocol.toml から Pi 側 Python パーサと STM32 側 C ヘッダを生成する。

    python3 raspi/proto/generate.py            生成
    python3 raspi/proto/generate.py --check    生成物が最新かだけ確認（CI 用）

パケット定義を Pi 側と STM32 側の2箇所に手書きすると必ずズレる
（実際に v0.4 の策定中、フィールド順のズレで2往復した）。定義は protocol.toml だけに置く。
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

PROTO_DIR = Path(__file__).resolve().parent
SPEC_PATH = PROTO_DIR / "protocol.toml"
OUT_DIR = PROTO_DIR / "generated"
PY_OUT = OUT_DIR / "packets.py"
H_OUT = OUT_DIR / "surge_proto.h"

# type -> (struct 文字, C 型, バイト数)
TYPES = {
    "u8": ("B", "uint8_t", 1),
    "i8": ("b", "int8_t", 1),
    "u16": ("H", "uint16_t", 2),
    "i16": ("h", "int16_t", 2),
    "u32": ("I", "uint32_t", 4),
    "i32": ("i", "int32_t", 4),
    "f32": ("f", "float", 4),
}

BANNER = "AUTO-GENERATED by raspi/proto/generate.py from protocol.toml — DO NOT EDIT"


# ── 解析 ────────────────────────────────────────────────────────────────

def class_name(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


def struct_fmt(fields: list[dict]) -> str:
    """フィールド列から struct フォーマット文字列を作る（連続する同型は数量指定にまとめる）。"""
    chars: list[str] = []
    for f in fields:
        if f["type"] == "bytes":
            continue
        chars += [TYPES[f["type"]][0]] * f.get("count", 1)

    out, i = [], 0
    while i < len(chars):
        j = i
        while j < len(chars) and chars[j] == chars[i]:
            j += 1
        n = j - i
        out.append(chars[i] if n == 1 else f"{n}{chars[i]}")
        i = j
    return "<" + "".join(out)


def payload_size(fields: list[dict]) -> int:
    return sum(TYPES[f["type"]][2] * f.get("count", 1)
               for f in fields if f["type"] != "bytes")


def load_spec() -> dict:
    with SPEC_PATH.open("rb") as fp:
        spec = tomllib.load(fp)

    seen_type: dict[int, str] = {}
    for p in spec["packets"]:
        name, fields = p["name"], p["fields"]

        if p["type"] in seen_type:
            raise SystemExit(f"TYPE 0x{p['type']:02X} が重複: {seen_type[p['type']]} と {name}")
        seen_type[p["type"]] = name

        # 方向規約: 0x01-0x0F = STM32→Pi, 0x10-0x1F = Pi→STM32
        want = "s2p" if p["type"] < 0x10 else "p2s"
        if p["dir"] != want:
            raise SystemExit(f"{name}: TYPE 0x{p['type']:02X} は dir='{want}' のはず（'{p['dir']}' になっている）")

        for k, f in enumerate(fields):
            if f["type"] == "bytes" and k != len(fields) - 1:
                raise SystemExit(f"{name}.{f['name']}: bytes は末尾フィールドにしか置けない")
            if f["type"] != "bytes" and f["type"] not in TYPES:
                raise SystemExit(f"{name}.{f['name']}: 未知の型 '{f['type']}'")

        p["_fmt"] = struct_fmt(fields)
        p["_size"] = payload_size(fields)

        # 固定長パケットは protocol.toml の len と実サイズが一致することを検証する
        if not p.get("variable"):
            if p["_size"] != p["len"]:
                raise SystemExit(
                    f"{name}: len={p['len']} だがフィールド合計は {p['_size']} バイト")
            if p["len"] > spec["frame"]["max_payload"]:
                raise SystemExit(f"{name}: LEN が max_payload を超えている")

    return spec


# ── Python 生成 ─────────────────────────────────────────────────────────

def gen_python(spec: dict) -> str:
    L: list[str] = [
        f'"""{BANNER}',
        "",
        f'仕様: {spec["meta"]["doc"]}',
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import struct",
        "from dataclasses import dataclass, field",
        "from typing import ClassVar",
        "",
        f'PROTOCOL_VERSION = 0x{spec["meta"]["protocol_version"]:04X}',
        f'SYNC = bytes({spec["frame"]["sync"]})',
        f'FRAME_OVERHEAD = {spec["frame"]["overhead"]}',
        f'HEADER_SIZE = {spec["frame"]["header_size"]}',
        f'MAX_PAYLOAD = {spec["frame"]["max_payload"]}',
        f'CRC_CHECK_VALUE = 0x{spec["crc"]["check"]:04X}',
        "",
    ]

    # ビット定義・enum・param_id
    for group, items in spec.get("bits", {}).items():
        L.append(f"# {items.get('comment', group)}")
        for k, v in items.items():
            if k == "comment":
                continue
            L.append(f"{group}_{k} = 0x{v:08X}" if v > 0xFF else f"{group}_{k} = 0x{v:02X}")
        L.append("")

    for group, items in spec.get("enums", {}).items():
        L.append(f"class {class_name(group)}:")
        if "comment" in items:
            L.append(f'    """{items["comment"]}"""')
        for k, v in items.items():
            if k == "comment":
                continue
            L.append(f"    {k} = {v}")
        L.append("")

    params = spec.get("params", {})
    if params:
        L.append("class Param:")
        L.append(f'    """{params.get("comment", "param_id")}"""')
        for k, v in params.items():
            if k == "comment":
                continue
            L.append(f"    {k} = 0x{v:04X}")
        L.append("")

    # パケット
    for p in spec["packets"]:
        cls = class_name(p["name"])
        fields = p["fields"]
        variable = bool(p.get("variable"))

        L.append(f"_S_{p['name']} = struct.Struct({p['_fmt']!r})")
        L.append("")
        L.append("")
        L.append("@dataclass(slots=True)")
        L.append(f"class {cls}:")
        doc = p.get("doc") or p["name"]
        L.append(f'    """0x{p["type"]:02X} {p["dir"]} — {doc}"""')
        L.append("")
        L.append(f"    TYPE: ClassVar[int] = 0x{p['type']:02X}")
        L.append(f"    NAME: ClassVar[str] = {p['name']!r}")
        L.append(f"    DIR: ClassVar[str] = {p['dir']!r}")
        L.append(f"    LEN: ClassVar[int | None] = {'None' if variable else p['len']}")
        L.append(f"    FMT: ClassVar[str] = {p['_fmt']!r}")
        if "rate_hz" in p:
            L.append(f"    RATE_HZ: ClassVar[float] = {p['rate_hz']}")

        # scale/unit のメタ情報（GUI と SI 変換で使う）
        meta = {f["name"]: (f.get("scale"), f.get("unit"))
                for f in fields if f.get("scale") or f.get("unit")}
        if meta:
            L.append(f"    META: ClassVar[dict] = {meta!r}")
        L.append("")

        for f in fields:
            n, t = f["name"], f["type"]
            cnt = f.get("count")
            note = f"  # {f['note']}" if "note" in f else ""
            if t == "bytes":
                L.append(f"    {n}: bytes = b''{note}")
            elif cnt:
                L.append(f"    {n}: list[int] = field(default_factory=lambda: [0] * {cnt}){note}")
            else:
                L.append(f"    {n}: {'float' if t == 'f32' else 'int'} = {'0.0' if t == 'f32' else '0'}{note}")

        if not fields:
            L.append("    pass")
        L.append("")

        # decode
        L.append("    @classmethod")
        L.append(f"    def decode(cls, payload: bytes) -> '{cls}':")
        fixed = p["_size"]
        if variable:
            L.append(f"        v = _S_{p['name']}.unpack_from(payload)")
        elif fixed:
            L.append(f"        v = _S_{p['name']}.unpack(payload)")

        args, idx = [], 0
        for f in fields:
            n, t, cnt = f["name"], f["type"], f.get("count")
            if t == "bytes":
                args.append(f"{n}=bytes(payload[{fixed}:])")
            elif cnt:
                args.append(f"{n}=list(v[{idx}:{idx + cnt}])")
                idx += cnt
            else:
                args.append(f"{n}=v[{idx}]")
                idx += 1
        if args:
            L.append(f"        return cls({', '.join(args)})")
        else:
            L.append("        return cls()")
        L.append("")

        # encode
        L.append("    def encode(self) -> bytes:")
        packargs = []
        tail = None
        for f in fields:
            if f["type"] == "bytes":
                tail = f["name"]
            elif f.get("count"):
                packargs.append(f"*self.{f['name']}")
            else:
                packargs.append(f"self.{f['name']}")
        body = f"_S_{p['name']}.pack({', '.join(packargs)})" if packargs else "b''"
        if tail:
            L.append(f"        return {body} + self.{tail}")
        else:
            L.append(f"        return {body}")
        L.append("")
        L.append("")

    # レジストリ
    L.append("ALL = (")
    for p in spec["packets"]:
        L.append(f"    {class_name(p['name'])},")
    L.append(")")
    L.append("")
    L.append("BY_TYPE = {c.TYPE: c for c in ALL}")
    L.append("BY_NAME = {c.NAME: c for c in ALL}")
    L.append("")
    L.append("#: TYPE -> 期待 LEN。None は可変長（LOG）")
    L.append("EXPECTED_LEN = {c.TYPE: c.LEN for c in ALL}")
    L.append("")
    L.append("#: 受信側が期待する TYPE 集合")
    L.append('S2P_TYPES = frozenset(c.TYPE for c in ALL if c.DIR == "s2p")')
    L.append('P2S_TYPES = frozenset(c.TYPE for c in ALL if c.DIR == "p2s")')
    L.append("")
    return "\n".join(L)


# ── C ヘッダ生成 ────────────────────────────────────────────────────────

def gen_header(spec: dict) -> str:
    L: list[str] = [
        f"/* {BANNER}",
        " *",
        f' * 仕様: {spec["meta"]["doc"]}',
        " * このファイルは Pi 側リポジトリで生成される。STM32 側は編集せずそのまま取り込むこと。",
        " */",
        "#ifndef SURGE_PROTO_H",
        "#define SURGE_PROTO_H",
        "",
        "#include <stdint.h>",
        "",
        f'#define SURGE_PROTOCOL_VERSION  0x{spec["meta"]["protocol_version"]:04X}u',
        f'#define SURGE_SYNC0             0x{spec["frame"]["sync"][0]:02X}u',
        f'#define SURGE_SYNC1             0x{spec["frame"]["sync"][1]:02X}u',
        f'#define SURGE_FRAME_OVERHEAD    {spec["frame"]["overhead"]}u',
        f'#define SURGE_HEADER_SIZE       {spec["frame"]["header_size"]}u',
        f'#define SURGE_MAX_PAYLOAD       {spec["frame"]["max_payload"]}u',
        "",
        f'/* CRC: {spec["crc"]["name"]}  poly=0x{spec["crc"]["poly"]:04X} '
        f'init=0x{spec["crc"]["init"]:04X}  "123456789" -> 0x{spec["crc"]["check"]:04X} */',
        f'#define SURGE_CRC_POLY          0x{spec["crc"]["poly"]:04X}u',
        f'#define SURGE_CRC_INIT          0x{spec["crc"]["init"]:04X}u',
        f'#define SURGE_CRC_CHECK         0x{spec["crc"]["check"]:04X}u',
        "",
        "/* ── パケット種別 ─────────────────────────────────────────── */",
    ]

    width = max(len(p["name"]) for p in spec["packets"]) + 4
    for direction, label in (("s2p", "STM32 -> Pi"), ("p2s", "Pi -> STM32")):
        L.append(f"/* {label} */")
        for p in spec["packets"]:
            if p["dir"] != direction:
                continue
            length = "可変" if p.get("variable") else f'{p["len"]}'
            L.append(f'#define PKT_{p["name"]:<{width}} 0x{p["type"]:02X}u   /* LEN = {length} */')
        L.append("")

    L.append("/* ── ビット定義 ───────────────────────────────────────────── */")
    for group, items in spec.get("bits", {}).items():
        L.append(f'/* {items.get("comment", group)} */')
        w = max(len(k) for k in items if k != "comment") + len(group) + 2
        for k, v in items.items():
            if k == "comment":
                continue
            L.append(f'#define {group + "_" + k:<{w}} 0x{v:08X}u' if v > 0xFF
                     else f'#define {group + "_" + k:<{w}} 0x{v:02X}u')
        L.append("")

    L.append("/* ── enum / param_id ──────────────────────────────────────── */")
    for group, items in spec.get("enums", {}).items():
        for k, v in items.items():
            if k == "comment":
                continue
            L.append(f"#define {group}_{k:<20} {v}u")
        L.append("")
    for k, v in spec.get("params", {}).items():
        if k == "comment":
            continue
        L.append(f"#define PARAM_{k:<18} 0x{v:04X}u")
    L.append("")

    L.append("/* ── パケット構造体 ───────────────────────────────────────── */")
    L.append("/* ペイロードはフレーム先頭から5バイト目に始まるため u32/i32 が4バイト境界に乗らない。")
    L.append(" * 非 packed 構造体へのキャストは未定義動作。受信は必ず memcpy 経由で行うこと。 */")
    L.append("#pragma pack(push, 1)")
    L.append("")

    for p in spec["packets"]:
        if p.get("variable"):
            L.append(f'/* {p["name"]} (0x{p["type"]:02X}) は可変長。'
                     f'[severity : uint8_t][message : char[]] として手で組む */')
            L.append("")
            continue
        if not p["fields"]:
            L.append(f'/* {p["name"]} (0x{p["type"]:02X}) はペイロードなし (LEN = 0) */')
            L.append("")
            continue

        L.append(f'/* {p["name"]} (0x{p["type"]:02X}) — {p.get("doc", "")} */')
        L.append("typedef struct {")
        rows = []
        for f in p["fields"]:
            ctype = TYPES[f["type"]][1]
            arr = f'[{f["count"]}]' if f.get("count") else ""
            bits = []
            if f.get("scale"):
                bits.append(f'{f["scale"]:g} {f.get("unit", "")}'.strip())
            elif f.get("unit"):
                bits.append(f["unit"])
            if f.get("note"):
                bits.append(f["note"])
            rows.append((ctype, f"{f['name']}{arr};", "  ".join(bits)))
        tw = max(len(r[0]) for r in rows)
        nw = max(len(r[1]) for r in rows)
        for ctype, decl, comment in rows:
            line = f"    {ctype:<{tw}} {decl:<{nw}}"
            L.append(f"{line}  /* {comment} */".rstrip() if comment else line.rstrip())
        L.append(f'}} surge_{p["name"].lower()}_t;')
        L.append("")

    L.append("#pragma pack(pop)")
    L.append("")
    L.append("/* サイズ検証。#pragma pack の付け忘れをビルド時に検出する。 */")
    for p in spec["packets"]:
        if p.get("variable") or not p["fields"]:
            continue
        t = f'surge_{p["name"].lower()}_t'
        L.append(f'_Static_assert(sizeof({t}) == {p["len"]}, "{t} size mismatch");')
    L.append("")
    L.append("#endif /* SURGE_PROTO_H */")
    return "\n".join(L)


# ── エントリポイント ────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="生成物が最新かだけ確認する")
    args = ap.parse_args()

    spec = load_spec()
    outputs = {PY_OUT: gen_python(spec), H_OUT: gen_header(spec)}

    if args.check:
        stale = [p.name for p, text in outputs.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print(f"生成物が古い: {', '.join(stale)}  → python3 {Path(__file__).name} を実行してください",
                  file=sys.stderr)
            return 1
        print("生成物は protocol.toml と一致しています")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "__init__.py").write_text(
        f'"""{BANNER}"""\n\nfrom .packets import *  # noqa: F401,F403\n', encoding="utf-8")
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"生成: {path.relative_to(PROTO_DIR.parent.parent)}")

    total = sum(p["len"] + spec["frame"]["overhead"]
                for p in spec["packets"] if not p.get("variable"))
    print(f"パケット {len(spec['packets'])} 種、固定長フレーム合計 {total} バイト")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
