#!/usr/bin/env python3
"""`raspi/msgs/types.py` から GUI 用の TypeScript 型を生成する。

    python3 config/gen_msgs.py            生成
    python3 config/gen_msgs.py --check    生成物が最新かだけ確認する

## なぜ要るか（2026-08-21 のレビュー 🟠2）

バスのメッセージ型が **Python と TypeScript に手書きで二重管理**されていた。
`VehicleState` だけで 45 フィールドの完全な写経で、git 履歴を見ると
`types.py` の変更 10 回のうち 7 回が `gui/src/types.ts` と同一コミットだった。

危ないのは、**片方だけ直してもどのツールもエラーを出さない**こと。`tsc` は
Pi 側を知らず、pytest は GUI を知らない。フィールドを 1 つ改名すると GUI は
静かに `undefined` を読み、画面には空欄か `NaN` が出るだけ。50Hz で流れる値
なので、気づくのは走行後。

`protocol.toml → Python/C`（`raspi/proto/generate.py`）と
`vehicle.toml → TypeScript`（`config/generate.py`）で既に採っている形を、
メッセージ定義にも適用する。**`types.py` が唯一の正。**

## 型はどこから取るか

- **型そのもの**は `msgspec.inspect` から。アノテーションを字面で解釈しない
  （`list[float] | None` のような書き方を自前でパースし始めると必ずずれる）
- **コメント**は `ast` + 元のソース行から。`#:` で書かれた単位・注意書きは
  GUI 側でも読めないと意味が無い（「`batt_current` は回生中 0 に張り付く」
  のような**知らないと誤読する**情報が多い）
- **固定長**はクラスを 1 つ実体化して既定値の長さを測る。`[0.0] * 4` の 4 は
  アノテーションには出てこないが、GUI 側ではタプル型で表現したい（🟠3-②）

## 生成しないもの

GUI にしか無い型（`MapData`・`Snapshot`・`ControlStatus`・`CmdOut` など）は
Python 側に対応物が無いので `gui/src/types.ts` に手書きのまま残す。
ここが生成するのは**バスに流れるメッセージの写しだった部分だけ**。
"""

from __future__ import annotations

import argparse
import ast
import sys
import textwrap
from pathlib import Path

CONFIG_DIR = Path(__file__).resolve().parent
REPO_ROOT = CONFIG_DIR.parent
sys.path.insert(0, str(REPO_ROOT))

import msgspec.inspect as mi  # noqa: E402

from raspi.msgs import types as msgtypes  # noqa: E402
from raspi.msgs.schema import MIRRORED, schema_version  # noqa: E402

TYPES_PY = REPO_ROOT / "raspi" / "msgs" / "types.py"
TS_OUT = REPO_ROOT / "gui" / "src" / "generated" / "msgs.ts"

BANNER = ("AUTO-GENERATED by config/gen_msgs.py from raspi/msgs/types.py "
          "— DO NOT EDIT")

#: 生成する型と、TypeScript 側での名前。
#: **バスに流れて GUI が読むものだけ。** `DriveCmd` は GUI → Pi 方向で
#: WS の JSON 形（`CmdOut`）が別にあるため、ここでは生成しない
EXPORTS: dict[str, str] = {
    "VehicleState": "VehicleState",
    "Scan": "Scan",
    "LinkDiag": "LinkDiag",
    "AutoState": "AutoState",
    # `/ws/map` で届く生のメッセージ。展開後の描画用の型（`MapData`）とは別物
    "AutoMap": "AutoMapMsg",
}

#: Python では `str` だが、TS では**取りうる値が決まっている**もの。
#: 生成器が推測すると嘘になるので、ここだけ人間が宣言する。
#: **`types.py` 側の docstring と一致させること**（増やしたらここも足す）
LITERAL_OVERRIDES: dict[tuple[str, str], str] = {
    ("LinkDiag", "health"): "'INIT' | 'OK' | 'DEGRADED' | 'FAULT'",
}

#: タプル型で書く固定長の上限。これを超えたら普通の配列にする。
#: `Scan.dist` は 360 要素で、タプルにしても読めないうえ `tsc` が遅くなる
MAX_TUPLE_LEN = 8

#: 固定長として扱わないフィールド。既定値がたまたま非空なだけで、
#: 実行時には長さが変わるもの。**ここを間違えるとタプル型が嘘をつく**
VARIABLE_LENGTH: frozenset[tuple[str, str]] = frozenset({
    # 今のところ該当なし（`faults` や `obstacles` は既定が空リストなので
    # 長さ 0 = 可変として自動的に扱われる）
})


# ── 型の変換 ────────────────────────────────────────────────────────────

def ts_type(t) -> str:
    """`msgspec.inspect` の型 → TypeScript の型。"""
    if isinstance(t, mi.UnionType):
        # `X | None` は TS でも `X | null`。順序は Python の宣言順のまま
        return " | ".join(ts_type(x) for x in t.types)
    if isinstance(t, mi.ListType):
        inner = ts_type(t.item_type)
        # `A | B` を含む要素は括弧が要る（`(number | null)[]`）
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if isinstance(t, mi.DictType):
        return f"Record<{ts_type(t.key_type)}, {ts_type(t.value_type)}>"
    if isinstance(t, (mi.IntType, mi.FloatType)):
        return "number"
    if isinstance(t, mi.BoolType):
        return "boolean"
    if isinstance(t, mi.StrType):
        return "string"
    if isinstance(t, mi.BytesType):
        # msgpack の bin。`@msgpack/msgpack` は Uint8Array で返す
        return "Uint8Array"
    if isinstance(t, mi.NoneType):
        return "null"
    if isinstance(t, mi.AnyType):
        return "unknown"
    raise TypeError(f"TypeScript へ落とし方が決まっていない型: {t!r}  "
                    f"→ config/gen_msgs.py の ts_type() に足してください")


def tuple_type(item_ts: str, n: int) -> str:
    """固定長を TS のタプル型で書く。`[number, number, number, number]`。"""
    return "[" + ", ".join([item_ts] * n) + "]"


# ── コメントの収集 ──────────────────────────────────────────────────────

def _strip_marker(text: str) -> str:
    """`#:` の直後の空白を **1 個だけ**落とす。

    全部 lstrip すると `#:     sensor = ...` のような**字下げした計算例**が
    左端に寄って、Markdown のコードブロックとして読めなくなる。
    """
    return (text[1:] if text.startswith(" ") else text).rstrip()


def collect_comments() -> dict[tuple[str, str], list[str]]:
    """`types.py` のフィールドに付いた `#:` コメントを拾う。

    2 つの書き方の両方を拾う（`types.py` はどちらも使っている）:

        #: 前の行に書く形。複数行になることもある
        wheel_speed: list[float] = ...

        rot_speed_dps: float = 0.0    #: 行末に書く形

    docstring から拾わないのは、フィールド単位の情報だから。
    **単位と注意書きが GUI 側に渡らないと、型だけ合っていても誤読する。**
    """
    src = TYPES_PY.read_text(encoding="utf-8")
    lines = src.splitlines()
    tree = ast.parse(src)
    out: dict[tuple[str, str], list[str]] = {}

    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            name = stmt.target.id
            parts: list[str] = []

            # 直前の連続した `#:` 行（先頭の行から順に積む）
            i = stmt.lineno - 2                     # lineno は 1 始まり
            before: list[str] = []
            while i >= 0 and lines[i].strip().startswith("#:"):
                before.append(_strip_marker(lines[i].strip()[2:]))
                i -= 1
            parts.extend(reversed(before))

            # 行末の `#:`（複数行にまたがる宣言があるので終端行を探す）
            end = getattr(stmt, "end_lineno", stmt.lineno) - 1
            tail = lines[end].split("#:", 1)
            if len(tail) == 2:
                parts.append(_strip_marker(tail[1]))

            # **行の構造は保つ。** 1行に潰すと、`sector_dur_us` のように
            # コメント中に計算例を書いてあるものが読めなくなる
            while parts and not parts[0].strip():
                parts.pop(0)
            while parts and not parts[-1].strip():
                parts.pop()
            if parts:
                out[(node.name, name)] = parts
    return out


def ts_comment(lines: list[str], indent: str) -> list[str]:
    """`#:` コメントを TSDoc（`/** ... */`）に落とす。

    **原文の行の切れ目をそのまま使う。** Markdown の強調（`**…**`）や
    バッククォートも通す——元がその形で書かれており、エディタのホバーでも
    そのまま読めるため。整形し直すと、コメント中の計算例が1行に潰れる。
    """
    # `*/` がコメント中にあるとブロックが途中で閉じる
    body = [ln.replace("*/", "*\\/") for ln in lines]
    if len(body) == 1 and len(indent) + len(body[0]) < 96:
        return [f"{indent}/** {body[0].strip()} */"]
    out = [f"{indent}/**"]
    out += [f"{indent} * {ln}".rstrip() for ln in body]
    out.append(f"{indent} */")
    return out


# ── 生成 ────────────────────────────────────────────────────────────────

def class_doc(cls) -> str:
    """クラスの docstring の**先頭段落だけ**。全文は Python 側で読む。"""
    doc = (cls.__doc__ or "").strip()
    if not doc:
        return ""
    para: list[str] = []
    for line in doc.splitlines():
        if not line.strip():
            break
        para.append(line.strip())
    return " ".join(para)


def gen_ts() -> str:
    comments = collect_comments()
    classes = [getattr(msgtypes, n) for n in EXPORTS]
    # **札（`schema_version`）の対象と生成の対象は同じ集合でなければならない。**
    # ずれると「型は変わったのに札は据え置き」という一番たちの悪い状態になる
    if {c.__name__ for c in classes} != {c.__name__ for c in MIRRORED}:
        raise SystemExit(
            "config/gen_msgs.py の EXPORTS と raspi/msgs/schema.py の MIRRORED が "
            "食い違っています。両方を同じ集合にしてください")
    infos = mi.multi_type_info(classes)

    L: list[str] = [
        f"// {BANNER}",
        "",
        "/**",
        " * バスのメッセージ型。**`raspi/msgs/types.py` から生成している。**",
        " *",
        " * 単位はすべて SI（m/s, rad, m, A, V, ℃）。km/h や度への変換は表示の直前",
        " * （`format.ts`）でだけ行う。ここで度に直すと、以降どの値に換算が掛かって",
        " * いるのか分からなくなる。",
        " *",
        " * このファイルを直接編集しない。`raspi/msgs/types.py` を直してから",
        " * `python3 config/gen_msgs.py` を再実行すること。CI が `--check` で見ている。",
        " */",
        "",
        "/**",
        " * この型定義そのものから決まる札（`raspi/msgs/schema.py`）。",
        " *",
        " * `/ws/telemetry` の各フレームに `schema` として入ってくる。**食い違ったら",
        " * その画面を信じてはいけない**——Pi 側だけ新しくなった GUI は、消えた",
        " * フィールドを静かに `undefined` として読み、空欄や `NaN` を出すだけで",
        " * 動き続ける。50Hz で流れる値なので、気づくのは走行後になる。",
        " *",
        " * **手で上げる版番号ではない。** `raspi/msgs/types.py` を触れば必ず変わり、",
        " * 触っていなければ絶対に変わらない（上げ忘れが起きない形にしてある）。",
        " */",
        f"export const MSGS_SCHEMA = 0x{schema_version():08x}",
        "",
    ]

    for cls, info in zip(classes, infos):
        py_name = cls.__name__
        ts_name = EXPORTS[py_name]
        # 固定長の判定に使う既定値。**引数なしで作れることが前提**
        # （`MsgBase` の docstring どおり全フィールドに既定値がある）
        sample = cls()

        doc = class_doc(cls)
        if doc:
            L.append("/**")
            for line in textwrap.wrap(doc, width=92):
                L.append(f" * {line}")
            if ts_name != py_name:
                L.append(" *")
                L.append(f" * Python 側の名前は `{py_name}`。")
            L.append(" */")
        L.append(f"export type {ts_name} = {{")

        for f in info.fields:
            key = (py_name, f.name)
            if key in comments:
                L += ts_comment(comments[key], "  ")
            if key in LITERAL_OVERRIDES:
                t = LITERAL_OVERRIDES[key]
            else:
                t = ts_type(f.type)
                # 固定長のリストはタプル型にする。**配列長の想定を型に持たせる**
                # （`noUncheckedIndexedAccess` と組み合わさって初めて効く）
                if isinstance(f.type, mi.ListType) and key not in VARIABLE_LENGTH:
                    n = len(getattr(sample, f.name, []))
                    if 1 <= n <= MAX_TUPLE_LEN:
                        t = tuple_type(ts_type(f.type.item_type), n)
            L.append(f"  {f.encode_name}: {t}")
        L.append("}")
        L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="生成物が最新かだけ確認する")
    args = ap.parse_args()

    text = gen_ts()

    if args.check:
        if not TS_OUT.exists() or TS_OUT.read_text(encoding="utf-8") != text:
            print(f"生成物が古い: {TS_OUT.relative_to(REPO_ROOT)}  "
                  f"→ python3 config/{Path(__file__).name} を実行してください",
                  file=sys.stderr)
            return 1
        print("生成物は raspi/msgs/types.py と一致しています")
        return 0

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(text, encoding="utf-8")
    n_fields = sum(len(i.fields) for i in mi.multi_type_info(
        [getattr(msgtypes, n) for n in EXPORTS]))
    print(f"生成: {TS_OUT.relative_to(REPO_ROOT)}  "
          f"（{len(EXPORTS)} 型 / {n_fields} フィールド）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
