#!/usr/bin/env python3
"""`vehicle.toml` の幾何パラメータから GUI 用 TypeScript 定数を生成する。

    python3 config/generate.py            生成
    python3 config/generate.py --check    生成物が最新かだけ確認する

GUI（TypeScript）は Python の `tomllib` を実行時に読めないため、`vehicle.toml` を
直接読む口を持てない。かといって手で `gui/src/render/*.tsx` に数値を書き写すと、
実車を測り直すたびに片方が古くなる（実際に wheelbase が 0.25→0.23 に変わったとき
GUI 側の描画定数だけ取り残された）。`raspi/proto/generate.py`（protocol.toml →
Python/C）と同じ考え方で、TOML を唯一の正としてここから生成する。

制御・知覚が使う値（`raspi/core/vehicle.py` の `Vehicle`）は Python がそのまま
`vehicle.toml` を読むので対象外。ここで生成するのは GUI の描画・スライダ上限が
必要とする幾何値だけ。
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

CONFIG_DIR = Path(__file__).resolve().parent
TOML_PATH = CONFIG_DIR / "vehicle.toml"
TS_OUT = CONFIG_DIR.parent / "gui" / "src" / "generated" / "vehicle.ts"

BANNER = "AUTO-GENERATED by config/generate.py from config/vehicle.toml — DO NOT EDIT"


def gen_ts(spec: dict) -> str:
    footprint = spec.get("footprint", []) or []
    pts = ", ".join(f"[{float(x)}, {float(y)}]" for x, y in footprint)
    return "\n".join([
        f"// {BANNER}",
        "",
        "/** 車両の幾何パラメータ。base_link（後輪車軸中心）基準。SI 単位。",
        " * `docs/architecture.md` §5.3 の `config/vehicle.toml` と同じ値。",
        " * ここを直接編集せず、`config/vehicle.toml` を直してから",
        " * `python3 config/generate.py` を再実行すること。 */",
        "export const VEHICLE = {",
        f"  wheelbase: {float(spec.get('wheelbase', 0))}, // m",
        f"  track: {float(spec.get('track', 0))}, // m",
        f"  maxSteer: {float(spec.get('max_steer', 0))}, // rad（路面舵角上限）",
        f"  wheelRadius: {float(spec.get('wheel_radius', 0))}, // m",
        "  /** 車体外形ポリゴン [m]。反時計回り */",
        f"  footprint: [{pts}] as const,",
        "} as const",
        "",
    ])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="生成物が最新かだけ確認する")
    args = ap.parse_args()

    with TOML_PATH.open("rb") as fp:
        spec = tomllib.load(fp)

    text = gen_ts(spec)

    if args.check:
        if not TS_OUT.exists() or TS_OUT.read_text(encoding="utf-8") != text:
            print(f"生成物が古い: {TS_OUT}  → python3 {Path(__file__).name} を実行してください",
                  file=sys.stderr)
            return 1
        print("生成物は vehicle.toml と一致しています")
        return 0

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(text, encoding="utf-8")
    print(f"生成: {TS_OUT.relative_to(CONFIG_DIR.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
